name: guardas_seguridad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  modal_progress_hud_nsn: ^0.5.1
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^7.0.1
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo_guardas.png
    - assets/persona.png
    - assets/sonido_error.mp3
    - assets/sonido_success.wav

flutter_icons:
  android: true
  ios: true
  # iOS necesita un image_path; puedes usar el mismo PNG
  image_path: "assets/CUC.png"                # 1024x1024
  # Android: adaptive icon
  adaptive_icon_background: "#FFFFFF"         # o "assets/logo_background.png"
  adaptive_icon_foreground: "assets/CUC.png" 
